site_name: Starboard
site_url: https://aquasecurity.github.io/starboard/
site_description: Kubernetes-native security toolkit
docs_dir: docs/
repo_name: GitHub
repo_url: https://github.com/aquasecurity/starboard
edit_uri: ""
copyright: Copyright 2019-2021 Aqua Security Software Ltd.

nav:
  - Introduction: index.md
  - Starboard CLI:
      - Overview: cli/index.md
      - Installation:
          - From the Binary Releases: cli/installation/binary-releases.md
          - Krew: cli/installation/krew.md
          - Docker: cli/installation/docker.md
          - From Source (Linux, macOS): cli/installation/source.md
      - Getting Started: cli/getting-started.md
      - Troubleshooting: cli/troubleshooting.md
  - Starboard Operator:
      - Overview: operator/index.md
      - Installation:
          - kubectl: operator/installation/kubectl.md
          - Helm: operator/installation/helm.md
          - Operator Lifecycle Manager: operator/installation/olm.md
          - Upgrade: operator/installation/upgrade.md
      - Getting Started: operator/getting-started.md
      - Configuration: operator/configuration.md
  - Starboard Settings: settings.md
  - Integrations:
      - Vulnerability Scanners:
          - Overview: integrations/vulnerability-scanners/index.md
          - Trivy: integrations/vulnerability-scanners/trivy.md
          - Aqua Enterprise: integrations/vulnerability-scanners/aqua-enterprise.md
      - Configuration Checkers:
          - Overview: integrations/config-checkers/index.md
          - Polaris: integrations/config-checkers/polaris.md
          - Conftest: integrations/config-checkers/conftest.md
      - Infrastructure Scanners:
          - Overview: integrations/infra-scanners/index.md
      - Private Registries: integrations/private-registries.md
      - Managed Registries: integrations/managed-registries.md
      - Octant Plugin: integrations/octant.md
      - Lens Extension: integrations/lens.md
  - Tutorials:
      - Manage Access to Security Reports: tutorials/manage_access_to_security_reports.md
  - Custom Resource Definitions:
      - Overview: crds/index.md
      - VulnerabilityReport: crds/vulnerability-report.md
      - ClusterVulnerabilityReport: crds/clustervulnerability-report.md
      - ConfigAuditReport: crds/configaudit-report.md
      - ClusterConfigAuditReport: crds/clusterconfigaudit-report.md
      - CISKubeBenchReport: crds/ciskubebench-report.md
      - KubeHunterReport: crds/kubehunter-report.md
  - Frequently Asked Questions: faq.md
  - Further Reading: further-reading.md

theme:
  name: material
  custom_dir: overrides
  language: 'en'
  logo: images/starboard-icon-white.svg

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true

# All data defined under extra is automatically exposed as a variable and can
# be used from the template. For example, {{ var.version }}.
#
# Requires pip install mike and pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aquasecurity
    - icon: fontawesome/brands/slack
      link: https://slack.aquasec.com/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCZd5NF4XJRaU-yfextsY-pw
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AquaSecTeam
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/aquasecteam/
  version:
    provider: mike
  var:
    prev_git_tag: "v0.14.0"
    chart_version: 0.9.1

# Requires pip install mkdocs-macros-plugin
plugins:
  - search
  - macros
